spring:
  application:
    name: auth-service

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ""
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    defer-datasource-initialization: true

  doc:
    springdoc:
      version: 2.2
      api-docs:
        path: /api-docs
      default-consumes-media-type: application/json
      default-produces-media-type: application/json
      swagger-ui:
        operations-sorter: alpha
        tags-sorter: alpha
        path: /swagger-ui.html
        disable-swagger-default-url: true
        doc-expansion: none
      paths-to-match: /**

server:
  port: 8410

jwt:
  secret: Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1
  expiration_time: 86400
  token_prefix: Bearer
  header_string: Authorization
  login_url: /api/account/login

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8310/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
